# define a makefile variable for the java compiler
#
JCC = javac -classpath opencsv-3.6.jar


# this target entry builds the Server class
MapReduceInhale.class: MapReduceThreading.java
	@$(JCC) MapReduceThreading.java
	@chmod +x A1


